//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("mdlAutoEcole", "lecon_ibfk_2", "eleve", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(autoEcoleWFv2.eleve), "lecon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(autoEcoleWFv2.lecon), true)]
[assembly: EdmRelationshipAttribute("mdlAutoEcole", "lecon_ibfk_1", "vehicule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(autoEcoleWFv2.vehicule), "lecon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(autoEcoleWFv2.lecon), true)]

#endregion

namespace autoEcoleWFv2
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class mdlAutoEcoleContainer : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet mdlAutoEcoleContainer à l'aide de la chaîne de connexion trouvée dans la section 'mdlAutoEcoleContainer' du fichier de configuration d'application.
        /// </summary>
        public mdlAutoEcoleContainer() : base("name=mdlAutoEcoleContainer", "mdlAutoEcoleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet mdlAutoEcoleContainer.
        /// </summary>
        public mdlAutoEcoleContainer(string connectionString) : base(connectionString, "mdlAutoEcoleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet mdlAutoEcoleContainer.
        /// </summary>
        public mdlAutoEcoleContainer(EntityConnection connection) : base(connection, "mdlAutoEcoleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<eleve> eleves
        {
            get
            {
                if ((_eleves == null))
                {
                    _eleves = base.CreateObjectSet<eleve>("eleves");
                }
                return _eleves;
            }
        }
        private ObjectSet<eleve> _eleves;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<lecon> lecons
        {
            get
            {
                if ((_lecons == null))
                {
                    _lecons = base.CreateObjectSet<lecon>("lecons");
                }
                return _lecons;
            }
        }
        private ObjectSet<lecon> _lecons;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<vehicule> vehicules
        {
            get
            {
                if ((_vehicules == null))
                {
                    _vehicules = base.CreateObjectSet<vehicule>("vehicules");
                }
                return _vehicules;
            }
        }
        private ObjectSet<vehicule> _vehicules;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet eleves. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToeleves(eleve eleve)
        {
            base.AddObject("eleves", eleve);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet lecons. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTolecons(lecon lecon)
        {
            base.AddObject("lecons", lecon);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet vehicules. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTovehicules(vehicule vehicule)
        {
            base.AddObject("vehicules", vehicule);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlAutoEcole", Name="eleve")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class eleve : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet eleve.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        public static eleve Createeleve(global::System.Int32 id)
        {
            eleve eleve = new eleve();
            eleve.id = id;
            return eleve;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateInscription
        {
            get
            {
                return _dateInscription;
            }
            set
            {
                OndateInscriptionChanging(value);
                ReportPropertyChanging("dateInscription");
                _dateInscription = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateInscription");
                OndateInscriptionChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateInscription;
        partial void OndateInscriptionChanging(Nullable<global::System.DateTime> value);
        partial void OndateInscriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> creditHoraire
        {
            get
            {
                return _creditHoraire;
            }
            set
            {
                OncreditHoraireChanging(value);
                ReportPropertyChanging("creditHoraire");
                _creditHoraire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creditHoraire");
                OncreditHoraireChanged();
            }
        }
        private Nullable<global::System.Int32> _creditHoraire;
        partial void OncreditHoraireChanging(Nullable<global::System.Int32> value);
        partial void OncreditHoraireChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlAutoEcole", "lecon_ibfk_2", "lecon")]
        public EntityCollection<lecon> lecons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lecon>("mdlAutoEcole.lecon_ibfk_2", "lecon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lecon>("mdlAutoEcole.lecon_ibfk_2", "lecon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlAutoEcole", Name="lecon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lecon : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet lecon.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="date">Valeur initiale de la propriété date.</param>
        /// <param name="effectueeOui_Non">Valeur initiale de la propriété effectueeOui_Non.</param>
        public static lecon Createlecon(global::System.Int32 id, global::System.DateTime date, global::System.Boolean effectueeOui_Non)
        {
            lecon lecon = new lecon();
            lecon.id = id;
            lecon.date = date;
            lecon.effectueeOui_Non = effectueeOui_Non;
            return lecon;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idEleve
        {
            get
            {
                return _idEleve;
            }
            set
            {
                OnidEleveChanging(value);
                ReportPropertyChanging("idEleve");
                _idEleve = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idEleve");
                OnidEleveChanged();
            }
        }
        private Nullable<global::System.Int32> _idEleve;
        partial void OnidEleveChanging(Nullable<global::System.Int32> value);
        partial void OnidEleveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> heure
        {
            get
            {
                return _heure;
            }
            set
            {
                OnheureChanging(value);
                ReportPropertyChanging("heure");
                _heure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("heure");
                OnheureChanged();
            }
        }
        private Nullable<global::System.Int32> _heure;
        partial void OnheureChanging(Nullable<global::System.Int32> value);
        partial void OnheureChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duree
        {
            get
            {
                return _duree;
            }
            set
            {
                OndureeChanging(value);
                ReportPropertyChanging("duree");
                _duree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duree");
                OndureeChanged();
            }
        }
        private Nullable<global::System.Int32> _duree;
        partial void OndureeChanging(Nullable<global::System.Int32> value);
        partial void OndureeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean effectueeOui_Non
        {
            get
            {
                return _effectueeOui_Non;
            }
            set
            {
                OneffectueeOui_NonChanging(value);
                ReportPropertyChanging("effectueeOui_Non");
                _effectueeOui_Non = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("effectueeOui_Non");
                OneffectueeOui_NonChanged();
            }
        }
        private global::System.Boolean _effectueeOui_Non;
        partial void OneffectueeOui_NonChanging(global::System.Boolean value);
        partial void OneffectueeOui_NonChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numImmaVehicule
        {
            get
            {
                return _numImmaVehicule;
            }
            set
            {
                OnnumImmaVehiculeChanging(value);
                ReportPropertyChanging("numImmaVehicule");
                _numImmaVehicule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numImmaVehicule");
                OnnumImmaVehiculeChanged();
            }
        }
        private global::System.String _numImmaVehicule;
        partial void OnnumImmaVehiculeChanging(global::System.String value);
        partial void OnnumImmaVehiculeChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlAutoEcole", "lecon_ibfk_2", "eleve")]
        public eleve eleve
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<eleve>("mdlAutoEcole.lecon_ibfk_2", "eleve").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<eleve>("mdlAutoEcole.lecon_ibfk_2", "eleve").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<eleve> eleveReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<eleve>("mdlAutoEcole.lecon_ibfk_2", "eleve");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<eleve>("mdlAutoEcole.lecon_ibfk_2", "eleve", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlAutoEcole", "lecon_ibfk_1", "vehicule")]
        public vehicule vehicule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("mdlAutoEcole.lecon_ibfk_1", "vehicule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("mdlAutoEcole.lecon_ibfk_1", "vehicule").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<vehicule> vehiculeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("mdlAutoEcole.lecon_ibfk_1", "vehicule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<vehicule>("mdlAutoEcole.lecon_ibfk_1", "vehicule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlAutoEcole", Name="vehicule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vehicule : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet vehicule.
        /// </summary>
        /// <param name="numImma">Valeur initiale de la propriété numImma.</param>
        /// <param name="enEtat">Valeur initiale de la propriété enEtat.</param>
        public static vehicule Createvehicule(global::System.String numImma, global::System.Boolean enEtat)
        {
            vehicule vehicule = new vehicule();
            vehicule.numImma = numImma;
            vehicule.enEtat = enEtat;
            return vehicule;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numImma
        {
            get
            {
                return _numImma;
            }
            set
            {
                if (_numImma != value)
                {
                    OnnumImmaChanging(value);
                    ReportPropertyChanging("numImma");
                    _numImma = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("numImma");
                    OnnumImmaChanged();
                }
            }
        }
        private global::System.String _numImma;
        partial void OnnumImmaChanging(global::System.String value);
        partial void OnnumImmaChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modele
        {
            get
            {
                return _modele;
            }
            set
            {
                OnmodeleChanging(value);
                ReportPropertyChanging("modele");
                _modele = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modele");
                OnmodeleChanged();
            }
        }
        private global::System.String _modele;
        partial void OnmodeleChanging(global::System.String value);
        partial void OnmodeleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String couleur
        {
            get
            {
                return _couleur;
            }
            set
            {
                OncouleurChanging(value);
                ReportPropertyChanging("couleur");
                _couleur = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("couleur");
                OncouleurChanged();
            }
        }
        private global::System.String _couleur;
        partial void OncouleurChanging(global::System.String value);
        partial void OncouleurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean enEtat
        {
            get
            {
                return _enEtat;
            }
            set
            {
                OnenEtatChanging(value);
                ReportPropertyChanging("enEtat");
                _enEtat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enEtat");
                OnenEtatChanged();
            }
        }
        private global::System.Boolean _enEtat;
        partial void OnenEtatChanging(global::System.Boolean value);
        partial void OnenEtatChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlAutoEcole", "lecon_ibfk_1", "lecon")]
        public EntityCollection<lecon> lecons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lecon>("mdlAutoEcole.lecon_ibfk_1", "lecon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lecon>("mdlAutoEcole.lecon_ibfk_1", "lecon", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
